name: Flatpak CI Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:kde-5.15-23.08
      options: --privileged
    strategy:
      matrix:
        arch: [x86_64]
    steps:
    - uses: actions/checkout@v4
    - name: Install packaging deps
      run: |
        dnf -y install gcc systemd-devel python3-devel libnotify poetry
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: yin-yang.flatpak
        manifest-path: sh.oskar.yin-yang.json
        cache-key: flatpak-builder-${{ github.sha }}
        arch: ${{ matrix.arch }}